import type { Language } from "./types";

const en = {
  title: "Limits",
  subtitle: "Public ChatGPT limits and the messages observed by this launcher.",
  notConfigured: "Not configured",
  setupTitle: "Keep track of the messages sent here",
  setupBody: "Set up tracking to detect your ChatGPT plan in the launcher browser. Available for Pro 5x ($100) and Pro 20x ($200).",
  setup: "Set up tracking",
  checking: "Checking your plan…",
  recheck: "Check plan again",
  browserBusy: "Wait for the current browser task or operation to finish before checking your plan.",
  loading: "Loading saved tracking…",
  refresh: "Refresh",
  loadError: "Could not load tracking.",
  staleError: "Could not refresh tracking. The last loaded snapshot is shown below.",
  actionError: "Could not complete this action.",
  sourceError: "Could not open the OpenAI reference.",
  zeroRisk: "Unavailable in Zero Risk",
  zeroRiskBody: "Plan detection and usage tracking are unavailable in Zero Risk mode. Public reference limits remain available.",
  proOnly: "Tracking is available for Pro plans only",
  unsupportedBody: "This account was not identified as Pro 5x ($100) or Pro 20x ($200). Plus and other plans cannot be tracked here; their numeric limits are unknown.",
  paused: "Tracking not active",
  active: "Launcher tracking on",
  estimate: "Estimated",
  observedTitle: "Observed usage",
  observedBody: "Messages recorded in local rolling windows, compared with the published reference.",
  scopeTitle: "Only activity through this launcher is counted",
  scopeBody: "Usage outside this launcher is excluded. These estimates are not your account’s remaining allowance. Rolling 24-hour and 7-day windows do not establish ChatGPT’s reset time.",
  noWindows: "No usage windows are available yet.",
  rollingDay: "Rolling 24 hours",
  rollingWeek: "Rolling 7 days",
  rollingHours: "Rolling {hours} hours",
  observed: "observed",
  nearLimit: "Observed usage has reached at least 75% of a reference limit",
  referenceCap: "Reference: {count} messages",
  uncertain: "Unassigned Pro messages in this window: {count}",
  sharedUnknown: "Includes {count} with an unknown Pro model",
  lowerBound: "At least {count}",
  modelTotalUnknown: "Model total unknown",
  attributionBody: "Some Pro messages have an unknown model. Model-specific counts are lower bounds; shared totals include those messages.",
  combined: "Both Pro models",
  history: "Saved history",
  historyBody: "The last 7 days of messages are saved on this device across launcher restarts. Recording begins when tracking is enabled; earlier activity is excluded.",
  totalMessages: "Messages · last 7 days",
  unknownPro: "Pro model not identified",
  unknownProBody: "These messages cannot be assigned to a specific Pro model.",
  since: "Tracking since",
  checked: "Plan checked",
  unknown: "Unknown",
  referenceTitle: "Public reference limits",
  referenceBody: "Chat allowances for GPT-6 Pro and GPT-5.6 Sol Pro. These are reference values, not account readings. Work and Codex allowances are separate.",
  asOf: "As of {date}",
  source: "OpenAI reference",
  referenceOnly: "Reference only",
  shared: "Shared across both Pro models",
  day: "{count} / day",
  week: "{count} / week",
  month: "{count} / month",
  otherPlans: "Plus & other plans",
  otherPlansBody: "Numeric allowances unknown. Launcher tracking is available only for Pro 5x ($100) and Pro 20x ($200).",
  businessBody: "Business allowances are shown for reference only. Business tracking is not supported.",
};

export type LimitsCopy = typeof en;

const zhCN: LimitsCopy = {
  title: "使用限额",
  subtitle: "ChatGPT 公开限额与此启动器观测到的消息用量。",
  notConfigured: "尚未设置",
  setupTitle: "跟踪在此发送的消息",
  setupBody: "设置跟踪后，将在启动器浏览器中检测您的 ChatGPT 套餐。支持 Pro 5x ($100) 和 Pro 20x ($200)。",
  setup: "设置用量跟踪",
  checking: "正在检查套餐…",
  recheck: "重新检查套餐",
  browserBusy: "请等待当前浏览器任务或操作完成后再检查套餐。",
  loading: "正在加载已保存的用量…",
  refresh: "刷新",
  loadError: "无法加载用量跟踪。",
  staleError: "无法刷新用量。下方显示上次加载的数据。",
  actionError: "无法完成此操作。",
  sourceError: "无法打开 OpenAI 参考资料。",
  zeroRisk: "零风险模式下不可用",
  zeroRiskBody: "零风险模式不支持套餐检测和用量跟踪。您仍可查看公开参考限额。",
  proOnly: "用量跟踪仅支持 Pro 套餐",
  unsupportedBody: "未能将此账户识别为 Pro 5x ($100) 或 Pro 20x ($200)。此处无法跟踪 Plus 及其他套餐，其具体限额未知。",
  paused: "跟踪未启用",
  active: "启动器跟踪已启用",
  estimate: "估算",
  observedTitle: "观测用量",
  observedBody: "本地滚动时间窗口内记录的消息数，对照公开参考限额。",
  scopeTitle: "仅统计通过此启动器发送的消息",
  scopeBody: "不包含启动器之外的用量。这些估算不代表账户剩余额度。滚动 24 小时和 7 天窗口不能确定 ChatGPT 的重置时间。",
  noWindows: "暂无用量窗口数据。",
  rollingDay: "滚动 24 小时",
  rollingWeek: "滚动 7 天",
  rollingHours: "滚动 {hours} 小时",
  observed: "已观测",
  nearLimit: "观测用量已达到参考限额的 75% 或以上",
  referenceCap: "参考限额：{count} 条消息",
  uncertain: "此窗口内模型未识别的 Pro 消息：{count}",
  sharedUnknown: "包含 {count} 条模型未知的 Pro 消息",
  lowerBound: "至少 {count}",
  modelTotalUnknown: "模型总用量未知",
  attributionBody: "部分 Pro 消息的模型未知。各模型的计数仅为下限；共享总数包含这些消息。",
  combined: "两个 Pro 模型合计",
  history: "已保存的历史",
  historyBody: "最近 7 天的消息记录保存在本设备上，重启后仍会保留。记录从启用跟踪时开始，不包含之前的活动。",
  totalMessages: "消息数 · 最近 7 天",
  unknownPro: "未识别 Pro 模型",
  unknownProBody: "这些消息无法归属于某个具体的 Pro 模型。",
  since: "跟踪开始时间",
  checked: "套餐检查时间",
  unknown: "未知",
  referenceTitle: "公开参考限额",
  referenceBody: "GPT-6 Pro 和 GPT-5.6 Sol Pro 在 Chat 中的额度。这些是参考值，并非账户实际读数。Work 和 Codex 使用独立额度。",
  asOf: "截至 {date}",
  source: "OpenAI 参考资料",
  referenceOnly: "仅供参考",
  shared: "两个 Pro 模型共享",
  day: "{count} / 天",
  week: "{count} / 周",
  month: "{count} / 月",
  otherPlans: "Plus 及其他套餐",
  otherPlansBody: "具体额度未知。启动器用量跟踪仅支持 Pro 5x ($100) 和 Pro 20x ($200)。",
  businessBody: "Business 额度仅供参考，不支持 Business 用量跟踪。",
};

const zhTW: LimitsCopy = {
  title: "使用額度",
  subtitle: "ChatGPT 公開額度與此啟動器觀測到的訊息用量。",
  notConfigured: "尚未設定",
  setupTitle: "追蹤在此傳送的訊息",
  setupBody: "設定追蹤後，將在啟動器瀏覽器中偵測您的 ChatGPT 方案。支援 Pro 5x ($100) 和 Pro 20x ($200)。",
  setup: "設定用量追蹤",
  checking: "正在檢查方案…",
  recheck: "重新檢查方案",
  browserBusy: "請等待目前的瀏覽器任務或操作完成後再檢查方案。",
  loading: "正在載入已儲存的用量…",
  refresh: "重新整理",
  loadError: "無法載入用量追蹤。",
  staleError: "無法更新用量。下方顯示上次載入的資料。",
  actionError: "無法完成此操作。",
  sourceError: "無法開啟 OpenAI 參考資料。",
  zeroRisk: "零風險模式下無法使用",
  zeroRiskBody: "零風險模式不支援方案偵測和用量追蹤。您仍可查看公開參考額度。",
  proOnly: "用量追蹤僅支援 Pro 方案",
  unsupportedBody: "未能將此帳戶識別為 Pro 5x ($100) 或 Pro 20x ($200)。此處無法追蹤 Plus 及其他方案，其具體額度未知。",
  paused: "追蹤尚未啟用",
  active: "啟動器追蹤已啟用",
  estimate: "估算",
  observedTitle: "觀測用量",
  observedBody: "本機滾動時間視窗內記錄的訊息數，對照公開參考額度。",
  scopeTitle: "僅統計透過此啟動器傳送的訊息",
  scopeBody: "不包含啟動器以外的用量。這些估算不代表帳戶剩餘額度。滾動 24 小時和 7 天視窗無法確定 ChatGPT 的重設時間。",
  noWindows: "暫無用量視窗資料。",
  rollingDay: "滾動 24 小時",
  rollingWeek: "滾動 7 天",
  rollingHours: "滾動 {hours} 小時",
  observed: "已觀測",
  nearLimit: "觀測用量已達參考額度的 75% 或以上",
  referenceCap: "參考額度：{count} 則訊息",
  uncertain: "此視窗內模型未識別的 Pro 訊息：{count}",
  sharedUnknown: "包含 {count} 則模型未知的 Pro 訊息",
  lowerBound: "至少 {count}",
  modelTotalUnknown: "模型總用量未知",
  attributionBody: "部分 Pro 訊息的模型未知。各模型的計數僅為下限；共用總數包含這些訊息。",
  combined: "兩個 Pro 模型合計",
  history: "已儲存的歷史",
  historyBody: "最近 7 天的訊息記錄儲存在本裝置上，重新啟動後仍會保留。記錄從啟用追蹤時開始，不包含之前的活動。",
  totalMessages: "訊息數 · 最近 7 天",
  unknownPro: "未識別 Pro 模型",
  unknownProBody: "這些訊息無法歸屬於某個特定的 Pro 模型。",
  since: "追蹤開始時間",
  checked: "方案檢查時間",
  unknown: "未知",
  referenceTitle: "公開參考額度",
  referenceBody: "GPT-6 Pro 和 GPT-5.6 Sol Pro 在 Chat 中的額度。這些是參考值，並非帳戶實際讀數。Work 和 Codex 使用獨立額度。",
  asOf: "截至 {date}",
  source: "OpenAI 參考資料",
  referenceOnly: "僅供參考",
  shared: "兩個 Pro 模型共用",
  day: "{count} / 天",
  week: "{count} / 週",
  month: "{count} / 月",
  otherPlans: "Plus 及其他方案",
  otherPlansBody: "具體額度未知。啟動器用量追蹤僅支援 Pro 5x ($100) 和 Pro 20x ($200)。",
  businessBody: "Business 額度僅供參考，不支援 Business 用量追蹤。",
};

const ja: LimitsCopy = {
  title: "利用上限",
  subtitle: "ChatGPT の公開上限と、このランチャーで観測したメッセージ数。",
  notConfigured: "未設定",
  setupTitle: "ここから送信したメッセージを記録",
  setupBody: "追跡を設定すると、ランチャーのブラウザで ChatGPT のプランを確認します。Pro 5x ($100) と Pro 20x ($200) に対応しています。",
  setup: "追跡を設定",
  checking: "プランを確認中…",
  recheck: "プランを再確認",
  browserBusy: "現在のブラウザタスクまたは操作が完了してから、プランを確認してください。",
  loading: "保存された記録を読み込み中…",
  refresh: "更新",
  loadError: "利用記録を読み込めませんでした。",
  staleError: "利用記録を更新できませんでした。前回読み込んだデータを表示しています。",
  actionError: "操作を完了できませんでした。",
  sourceError: "OpenAI の参考資料を開けませんでした。",
  zeroRisk: "Zero Risk では利用不可",
  zeroRiskBody: "Zero Risk モードではプランの検出と利用状況の追跡はできません。公開上限は引き続き参照できます。",
  proOnly: "追跡は Pro プランのみ対応",
  unsupportedBody: "このアカウントを Pro 5x ($100) または Pro 20x ($200) と確認できませんでした。Plus などのプランは追跡できず、具体的な上限値も不明です。",
  paused: "追跡は無効",
  active: "ランチャーの追跡が有効",
  estimate: "推定",
  observedTitle: "観測した使用量",
  observedBody: "ローカルのローリング期間内で記録されたメッセージ数を、公開上限と比較します。",
  scopeTitle: "このランチャー経由の利用のみ集計",
  scopeBody: "ランチャー以外での利用は含まれません。推定値はアカウントの残り利用枠ではありません。直近24時間・7日間の集計から ChatGPT のリセット時刻は特定できません。",
  noWindows: "集計期間のデータはまだありません。",
  rollingDay: "直近24時間",
  rollingWeek: "直近7日間",
  rollingHours: "直近{hours}時間",
  observed: "観測済み",
  nearLimit: "観測使用量が参考上限の75%以上に達しています",
  referenceCap: "参考上限：{count} メッセージ",
  uncertain: "この期間のモデル未特定 Pro メッセージ：{count}",
  sharedUnknown: "Pro モデル不明の {count} 件を含む",
  lowerBound: "少なくとも {count}",
  modelTotalUnknown: "モデル別の合計は不明",
  attributionBody: "モデルが不明な Pro メッセージがあります。モデル別の件数は下限値です。共有の合計にはこれらのメッセージも含まれます。",
  combined: "両 Pro モデルの合計",
  history: "保存された履歴",
  historyBody: "直近7日間のメッセージをこの端末に保存し、再起動後も保持します。記録は追跡の有効化時点から始まり、それ以前の利用は含まれません。",
  totalMessages: "メッセージ数 · 直近7日間",
  unknownPro: "Pro モデル未特定",
  unknownProBody: "これらのメッセージは特定の Pro モデルに割り当てられません。",
  since: "追跡開始",
  checked: "プラン確認日時",
  unknown: "不明",
  referenceTitle: "公開されている参考上限",
  referenceBody: "Chat での GPT-6 Pro と GPT-5.6 Sol Pro の利用枠です。参考値であり、アカウントから取得した値ではありません。Work と Codex の利用枠は別です。",
  asOf: "{date} 時点",
  source: "OpenAI の参考資料",
  referenceOnly: "参考情報のみ",
  shared: "両 Pro モデルで共有",
  day: "{count} / 日",
  week: "{count} / 週",
  month: "{count} / 月",
  otherPlans: "Plus・その他のプラン",
  otherPlansBody: "具体的な利用枠は不明です。ランチャーの追跡は Pro 5x ($100) と Pro 20x ($200) のみに対応しています。",
  businessBody: "Business の利用枠は参考情報です。Business の利用追跡には対応していません。",
};

const ko: LimitsCopy = {
  title: "사용 한도",
  subtitle: "ChatGPT의 공개 한도와 이 런처에서 관측한 메시지 사용량입니다.",
  notConfigured: "설정되지 않음",
  setupTitle: "여기에서 보낸 메시지를 기록하세요",
  setupBody: "추적을 설정하면 런처 브라우저에서 ChatGPT 요금제를 확인합니다. Pro 5x ($100) 및 Pro 20x ($200)을 지원합니다.",
  setup: "추적 설정",
  checking: "요금제 확인 중…",
  recheck: "요금제 다시 확인",
  browserBusy: "현재 브라우저 작업이나 실행 중인 작업이 끝난 후 요금제를 확인하세요.",
  loading: "저장된 사용 기록을 불러오는 중…",
  refresh: "새로고침",
  loadError: "사용 기록을 불러오지 못했습니다.",
  staleError: "사용 기록을 새로고침하지 못했습니다. 마지막으로 불러온 데이터를 표시합니다.",
  actionError: "이 작업을 완료하지 못했습니다.",
  sourceError: "OpenAI 참고 자료를 열지 못했습니다.",
  zeroRisk: "Zero Risk에서는 사용 불가",
  zeroRiskBody: "Zero Risk 모드에서는 요금제 확인과 사용량 추적을 사용할 수 없습니다. 공개 참고 한도는 계속 볼 수 있습니다.",
  proOnly: "추적은 Pro 요금제만 지원합니다",
  unsupportedBody: "이 계정을 Pro 5x ($100) 또는 Pro 20x ($200)으로 확인하지 못했습니다. Plus와 기타 요금제는 추적할 수 없으며 구체적인 한도도 알 수 없습니다.",
  paused: "추적 비활성",
  active: "런처 추적 활성",
  estimate: "추정치",
  observedTitle: "관측된 사용량",
  observedBody: "로컬 이동 집계 기간에 기록된 메시지 수를 공개 참고 한도와 비교합니다.",
  scopeTitle: "이 런처를 통한 사용만 집계합니다",
  scopeBody: "런처 외부에서의 사용량은 제외됩니다. 이 추정치는 계정의 남은 사용량이 아닙니다. 최근 24시간 및 7일 집계로는 ChatGPT의 초기화 시각을 알 수 없습니다.",
  noWindows: "아직 집계 기간 데이터가 없습니다.",
  rollingDay: "최근 24시간",
  rollingWeek: "최근 7일",
  rollingHours: "최근 {hours}시간",
  observed: "관측됨",
  nearLimit: "관측 사용량이 참고 한도의 75% 이상에 도달했습니다",
  referenceCap: "참고 한도: 메시지 {count}개",
  uncertain: "이 기간의 모델 미확인 Pro 메시지: {count}",
  sharedUnknown: "Pro 모델 미확인 메시지 {count}개 포함",
  lowerBound: "최소 {count}",
  modelTotalUnknown: "모델별 총사용량 미확인",
  attributionBody: "모델을 알 수 없는 Pro 메시지가 있습니다. 모델별 수치는 최솟값이며, 공유 합계에는 해당 메시지가 포함됩니다.",
  combined: "두 Pro 모델 합계",
  history: "저장된 기록",
  historyBody: "최근 7일의 메시지를 이 기기에 저장하며 재시작 후에도 유지합니다. 기록은 추적을 활성화한 시점부터 시작되며 이전 활동은 제외됩니다.",
  totalMessages: "메시지 · 최근 7일",
  unknownPro: "Pro 모델 미확인",
  unknownProBody: "이 메시지들은 특정 Pro 모델에 배정할 수 없습니다.",
  since: "추적 시작",
  checked: "요금제 확인",
  unknown: "알 수 없음",
  referenceTitle: "공개 참고 한도",
  referenceBody: "Chat에서의 GPT-6 Pro 및 GPT-5.6 Sol Pro 사용 한도입니다. 계정에서 읽은 값이 아닌 참고 값입니다. Work와 Codex 한도는 별도입니다.",
  asOf: "{date} 기준",
  source: "OpenAI 참고 자료",
  referenceOnly: "참고용",
  shared: "두 Pro 모델이 공유",
  day: "{count} / 일",
  week: "{count} / 주",
  month: "{count} / 월",
  otherPlans: "Plus 및 기타 요금제",
  otherPlansBody: "구체적인 사용 한도는 알 수 없습니다. 런처 추적은 Pro 5x ($100) 및 Pro 20x ($200)만 지원합니다.",
  businessBody: "Business 한도는 참고용입니다. Business 사용량 추적은 지원하지 않습니다.",
};

const copies: Record<Language, LimitsCopy> = { en, "zh-CN": zhCN, "zh-TW": zhTW, ja, ko };

export function limitsCopyFor(language: Language): LimitsCopy {
  return copies[language];
}
